---

- name: Install required packages
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ strongswan_packages }}"

- name: Setup /etc/ipsec.conf
  template:
    dest: /etc/ipsec.conf
    src: ipsec.conf.j2
    owner: root
    group: root
    mode: 0600
  notify:
  - ipsec rereadall and reload

- name: Create dirs for file-based credentials
  file:
    path: "/etc/ipsec.d/{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0700
  with_items:
  - private
  - certs
  - crls
  - cacerts
  - ocspcerts
  - aacerts
  - acerts
  - reqs

- include: ipsec-private.yaml
- include: ipsec-certs.yaml
- include: ipsec-crls.yaml
- include: ipsec-cacerts.yaml

- name: Start ipsec service
  service:
    name: ipsec
    state: started
    enabled: true

- name: Setup /etc/ipsec.secrets
  template:
    dest: /etc/ipsec.secrets
    src: ipsec.secrets.j2
    owner: root
    group: root
    mode: 0600
  notify:
  - ipsec rereadall and reload

- name: Configure sysctl
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
  with_items:
  - name: net.ipv4.ip_forward
    value: 1
  - name: net.ipv4.conf.all.forwarding
    value: 1
  - name: net.ipv6.conf.all.forwarding
    value: 0
  when: strongswan_manage_forwarding is defined and strongswan_manage_forwarding
