---

- name: Install required packages
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ strongswan_packages }}"

- name: Setup /etc/ipsec.conf
  template:
    dest: /etc/ipsec.conf
    src: ipsec.conf.j2
    owner: root
    group: root
    mode: 0644
  notify:
  - ipsec reload

- name: Create dirs for file-based credentials
  file:
    path: "/etc/ipsec.d/{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0700
  with_items:
  - aacerts
  - acerts
  - cacerts
  - certs
  - crls
  - ocspcerts
  - private
  - reqs

- name: Configure file-based credentials
  include: "ipsec-{{ item }}.yaml"
  with_items:
  - aacerts
  - acerts
  - cacerts
  - certs
  - crls
  - ocspcerts
  - private
  - reqs

- name: Start ipsec service
  service:
    name: ipsec
    state: started
    enabled: true

- name: Setup /etc/ipsec.secrets
  template:
    dest: /etc/ipsec.secrets
    src: ipsec.secrets.j2
    owner: root
    group: root
    mode: 0600
  notify:
  - ipsec reload

- name: Setup /etc/strongswan.d/charon-logging.conf
  template:
    dest: /etc/strongswan.d/charon-logging.conf
    src: charon-logging.conf.j2
    owner: root
    group: root
    mode: 0600
  notify:
  - ipsec reload
